//
//  UserViewController.swift
//  LoginProject
//
//  Created Alejandro Arjonilla Garcia on 02.05.18.
//  Copyright © 2018 Alejandro Arjonilla Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Auth0

class UserViewController: BaseRxController {
    
    @IBOutlet weak var usernameLabel: UILabel!
    @IBOutlet weak var emailLabel: UILabel!
    @IBOutlet weak var videosRecordedLabel: UILabel!
    @IBOutlet weak var proyectsEditedLabel: UILabel!
    @IBOutlet weak var proyectsSharedLabel: UILabel!
    @IBOutlet weak var userImageView: UIImageView!

    override func viewDidLoad() {
        loadProfile()
    }
    fileprivate func loadProfile() {
        if let profile = SessionManager.shared.profile {
            self.updateUI( profile)
        } else {
            self.login()
        }
    }
    private func updateUI(_ profile: UserInfo) {
        DispatchQueue.main.async {
            self.usernameLabel.text = profile.name
            self.emailLabel.text = profile.email
            if let url = profile.picture { self.userImageView.download(from: url) }
            let preferences = UserDefaults.standard
            self.videosRecordedLabel.text = "\(preferences.integer(forKey: ConfigPreferences().TOTAL_VIDEOS_RECORDED))"
            self.proyectsEditedLabel.text = "\(preferences.integer(forKey: ConfigPreferences().TOTAL_VIDEOS_SHARED))"
            self.proyectsSharedLabel.text = "\(preferences.integer(forKey: ConfigPreferences().TOTAL_VIDEOS_SHARED))"
        }
    }
    private func login() {
        SessionManager.shared.login {
            switch $0 {
            case .failure(let error):
                self.showWhisper(with: error.localizedDescription)
            case .success(let profile):
                self.updateUI(profile)
            }
        }
    }
}
