//
//  UserViewController.swift
//  LoginProject
//
//  Created Alejandro Arjonilla Garcia on 02.05.18.
//  Copyright © 2018 Alejandro Arjonilla Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserViewController: BaseRxController, UserViewProtocol {

    @IBOutlet weak var usernameButton: UIButton!
    @IBOutlet weak var emailButton: UIButton!
    @IBOutlet weak var videosRecordedLabel: UILabel!
    @IBOutlet weak var proyectsEditedLabel: UILabel!
    @IBOutlet weak var proyectsSharedLabel: UILabel!

    var presenter: UserPresenterProtocol?

    override func configureViews() {
        usernameButton.rx.tap.bind {
            self.presenter?.navigate()
            }.disposed(by: disposableBag)
        emailButton.rx.tap.bind {
            self.presenter?.navigate()
            }.disposed(by: disposableBag)
    }
}
