//
//  UserViewController.swift
//  LoginProject
//
//  Created Alejandro Arjonilla Garcia on 02.05.18.
//  Copyright © 2018 Alejandro Arjonilla Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserViewController: BaseRxController, UserViewProtocol {
    
    @IBOutlet weak var usernameButton: UIButton!
    @IBOutlet weak var emailButton: UIButton!
    @IBOutlet weak var videosRecordedLabel: UILabel!
    @IBOutlet weak var proyectsEditedLabel: UILabel!
    @IBOutlet weak var proyectsSharedLabel: UILabel!
    
    var presenter: UserPresenterProtocol?
    
    override func configureViews() {

    }
    override func viewWillAppear(_ animated: Bool) {
        loadProfile()
    }
    fileprivate func loadProfile() {
        SessionManager.shared.retrieveProfile {
            if let error = $0 {
                self.login()
            } else {
                guard let profile = SessionManager.shared.profile
                    else { return }
                self.usernameButton.setTitle(profile.name, for: .normal)
                self.emailButton.setTitle(profile.email, for: .normal)
            }
        }
    }    
    private func login() {
        SessionManager.shared.login {
            switch $0 {
            case .failure(let error):
                self.showWhisper(with: error.localizedDescription)
            case .success(let result):
                self.loadProfile()
            }
        }
    }
}
