//
//  LoginViewController.swift
//  vimojo
//
//  Created Jesus Huerta on 29/01/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginViewController: UIViewController, LoginViewProtocol {

	var presenter: LoginPresenterProtocol?

	@IBOutlet weak var emailTextField: UITextField!
	@IBOutlet weak var passwordTextField: UITextField!

	override func viewDidLoad() {
        super.viewDidLoad()
		setImageToEmail()
		setImageToPassword()
    }

	@IBAction func pushLogin(_ sender: Any) {
	}

	func setImageToEmail() {
		let imageView = UIImageView()
		let image = UIImage(named: "activity_rec_user_pressed")
		imageView.image = image
		imageView.frame = CGRect(x: 0, y: 0, width: 40, height: 15)
		imageView.contentMode = .scaleAspectFit
		emailTextField.leftViewMode = UITextFieldViewMode.always
		emailTextField.leftView = imageView
		emailTextField.addSubview(imageView)
	}

	func setImageToPassword() {
		let imageView = UIImageView()
		let image = UIImage(named: "activity_rec_user_pressed")
		imageView.image = image
		imageView.frame = CGRect(x: 0, y: 0, width: 40, height: 15)
		imageView.contentMode = .scaleAspectFit
		passwordTextField.leftViewMode = UITextFieldViewMode.always
		passwordTextField.leftView = imageView
		passwordTextField.addSubview(imageView)
	}
}
