//
//  KindOfProjectPresenter.swift
//  vimojo
//
//  Created Jesus Huerta on 02/04/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class KindOfProjectPresenter: KindOfProjectPresenterProtocol {
    func setKindOfProject(_: String) {
        // Save data
    }
    

    weak private var view: KindOfProjectViewProtocol?
    var interactor: KindOfProjectInteractorProtocol?
    private let router: KindOfProjectWireframeProtocol

    init(interface: KindOfProjectViewProtocol, interactor: KindOfProjectInteractorProtocol?, router: KindOfProjectWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
