//
//  KindOfProjectInteractor.swift
//  vimojo
//
//  Created Jesus Huerta on 02/04/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class KindOfProjectInteractor: KindOfProjectInteractorProtocol {

    weak var presenter: KindOfProjectPresenterProtocol?
}
