//
//  KindOfProjectProtocols.swift
//  vimojo
//
//  Created Jesus Huerta on 02/04/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol KindOfProjectWireframeProtocol: class {

}
//MARK: Presenter -
protocol KindOfProjectPresenterProtocol: class {
    func setKindOfProject(_: String)
}

//MARK: Interactor -
protocol KindOfProjectInteractorProtocol: class {

  var presenter: KindOfProjectPresenterProtocol?  { get set }
}

//MARK: View -
protocol KindOfProjectViewProtocol: class {

  var presenter: KindOfProjectPresenterProtocol?  { get set }
}
