//
//  KindOfProjectViewController.swift
//  vimojo
//
//  Created Jesus Huerta on 02/04/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

struct cellData {
    let cell: Int!
    let text: String!
}

class KindOfProjectViewController: UITableViewController {
    
    var arrayOfCellData = [cellData]()
    
    @IBOutlet weak var mainLabel: UILabel!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        arrayOfCellData = [cellData(cell: 1, text: "Falso directo"),
                           cellData(cell: 2, text: "Vídeo en bruto"),
                           cellData(cell: 3, text: "Colas"),
                           cellData(cell: 4, text: "Gráfico"),
                           cellData(cell: 5, text: "Piezas")]
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return arrayOfCellData.count
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = Bundle.main.loadNibNamed("KindOfProjectTableViewCell", owner: self, options: nil)?.first
        mainLabel.tag = arrayOfCellData[indexPath.row].cell
        mainLabel.text = arrayOfCellData[indexPath.row].text
        return cell as! UITableViewCell
    }
    
    override func tableView(_ tableView: UITableView, heightForFooterInSection section: Int) -> CGFloat {
        let tableViewHeightSize = arrayOfCellData.count * 50
        return self.view.bounds.height - CGFloat(tableViewHeightSize)
    }
    
    override func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
}
