//
//  PurchaseInteractor.swift
//  vimojo
//
//  Created Alejandro Arjonilla Garcia on 15/12/17.
//  Copyright © 2017 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PurchaseInteractor: PurchaseInteractorProtocol {

    weak var presenter: PurchasePresenterProtocol?
}
