//
//  PurchaseViewController.swift
//  vimojo
//
//  Created Alejandro Arjonilla Garcia on 15/12/17.
//  Copyright © 2017 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PurchaseViewController: UIViewController, PurchaseViewProtocol {

	var presenter: PurchasePresenterProtocol?
    var products: [ProductViewModel] = [] {
        didSet{
            
        }
    }
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.loadProducts()
    }

    func showError(with title: String, description: String) {
        let controller = UIAlertController.defaultAlert(title, description)
        self.present(controller, animated: true, completion: nil)
    }
}

extension UIAlertController {
    static var defaultAlert: (String, String) -> UIAlertController {
            return { title, description in
                let controller = UIAlertController(title: title, message: description, defaultActionButtonTitle: "OK", tintColor: .red)
                return controller
        }
    }
}
