update_fastlane

fastlane_version "2.31.0"

default_platform :ios

platform :ios do
  before_all do |lane, options|
    cocoapods
    ENV["SLACK_URL"] =  "https://hooks.slack.com/services/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"
    ENV["FASTLANE_USER"] =  "accounts@videona.com"
    ENV["FASTLANE_PASSWORD"] =  "Elendil1460!"
    keychain_entry = CredentialsManager::AccountManager.new(user: "accounts@videona.com")
    password = keychain_entry.password
    puts password
  end
  lane :certificates do
      match(type: 'development',app_identifier: ["com.videona.vimojo", "com.vimojo.thomsonfoundation", "com.vimojo.m4n", "com.vimojo.elconfidencial", "com.vimojo.RTVE"], readonly: true)
      match(type: 'adhoc', app_identifier: ["com.videona.vimojo", "com.vimojo.thomsonfoundation", "com.vimojo.m4n", "com.vimojo.elconfidencial", "com.vimojo.RTVE"], readonly: true)
  end
  # Fastfile actions accept additional configuration, but
  # don't worry, fastlane will prompt you for required
  # info which you can add here later
  lane :beta do
    match(type: 'adhoc', app_identifier: ["com.videona.vimojo"], readonly: true)
    increment_build_number(build_number: app_store_build_number + 1,
                            xcodeproj: "vimojo.xcodeproj")
    build_app(
      scheme: "vimojo",
      export_method: "ad-hoc"
    )

    # upload to Beta by Crashlytics
    crashlytics(
      # keys for organization: DEPRECATED-VideonaIOS
      api_token: "245a1998989c434deb37967cfa33882e5f169410",
      build_secret: "a4aace077e673d7b8bbb959e93125b49664db2b0da0cfb30de69381be101c379"
      # groups: ["Videona\ team"]
    )
  end
  lane :release do
    match(type: 'appstore', app_identifier: ["com.videona.vimojo"], readonly: true)
    increment_build_number(build_number: app_store_build_number + 1,
                            xcodeproj: "vimojo.xcodeproj")
    build_app(scheme: "vimojo",
          export_method: "app-store")
    upload_to_app_store(submit_for_review: true,
                        force: true)
    slack(message: "Successfully uploaded a new App Store build")
  end
end
