# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPad Pro (12.9-inch)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme "VimojoUITest"

# Where should the resulting screenshots be stored?
output_directory "./screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
# project "./vimojo.xcodeproj"
workspace "./vimojo.xcworkspace"

ios_version '11.2.5'

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane snapshot --help
