//
//  PermissionsProtocols.swift
//  vimojo
//
//  Created Jesus Huerta on 15/03/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol PermissionsWireframeProtocol: class {
    func goToRecorderScreen()
}
//MARK: Presenter -
protocol PermissionsPresenterProtocol: class {
    func askForCameraPermissionIfNeeded()
}

//MARK: Interactor -
protocol PermissionsInteractorProtocol: class {

  var presenter: PermissionsPresenterProtocol?  { get set }
}

//MARK: View -
protocol PermissionsViewProtocol: class {

  var presenter: PermissionsPresenterProtocol?  { get set }
}
