//
//  PermissionsInteractor.swift
//  vimojo
//
//  Created Jesus Huerta on 15/03/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PermissionsInteractor: PermissionsInteractorProtocol {

    weak var presenter: PermissionsPresenterProtocol?
}
