//
//  PermissionsRouter.swift
//  vimojo
//
//  Created Jesus Huerta on 15/03/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PermissionsRouter: PermissionsWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PermissionsViewController(nibName: nil, bundle: nil)
        let interactor = PermissionsInteractor()
        let router = PermissionsRouter()
        let presenter = PermissionsPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }

    func goToRecorderScreen() {        
        let appDelegate = UIApplication.shared.delegate as? AppDelegate
        let storyboard = UIStoryboard(name: "Record", bundle: Bundle.main)
        let viewController = storyboard.instantiateViewController(withIdentifier: "RecordController") as! RecordController
        appDelegate?.window?.rootViewController = viewController
    }
}
