//
//  PermissionsViewController.swift
//  vimojo
//
//  Created Jesus Huerta on 15/03/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Permission

class PermissionsViewController: UIViewController {
        
    var backgroundImage: UIImageView = UIImageView()
    internal var router: PermissionsWireframeProtocol?
    private var microphonePermission: Permission! = .microphone
    private var cameraPermission: Permission! = .camera
    private var photoGalleryPermission: Permission! = .photos
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.isNavigationBarHidden = true
        
        self.view.addSubview(backgroundImage)
        backgroundImage.snp.makeConstraints { (make) in
            make.center.equalToSuperview()
            make.width.equalToSuperview()
            make.height.equalToSuperview()
        }
        backgroundImage.image = #imageLiteral(resourceName: "PermissionLaunchImage.jpg")
        requestAll()
    }
    func requestAll() {
        DispatchQueue.main.async {
            self.askForCameraPermissionIfNeeded()
            self.askForGalleryPermissionIfNeeded()
            self.askForMicrophonePermissionIfNeeded()
        }
    }
    func updateStatus() {
        if microphonePermission.status == .authorized,
            cameraPermission.status == .authorized,
            photoGalleryPermission.status == .authorized {
            router?.goToRecorderScreen()
        } else {
            requestAll()
        }
    }
    func askForCameraPermissionIfNeeded() {
        cameraPermission.request { status in
            self.updateStatus()
        }
    }
    
    func askForMicrophonePermissionIfNeeded() {
        microphonePermission.request { status in
            self.updateStatus()
        }
    }
    
    func askForGalleryPermissionIfNeeded() {
        photoGalleryPermission.request { status in
            self.updateStatus()
        }
    }
}
