//
//  RecordingCameraConfigurationPresenter.swift
//  vimojo
//
//  Created Jesus Huerta on 19/01/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecordingCameraConfigurationPresenter: RecordingCameraConfigurationPresenterProtocol, RecordingCameraConfigurationInteractorOutputProtocol {

    weak private var view: RecordingCameraConfigurationViewProtocol?
    var interactor: RecordingCameraConfigurationInteractorInputProtocol?
    private let router: RecordingCameraConfigurationWireframeProtocol

    init(interface: RecordingCameraConfigurationViewProtocol, interactor: RecordingCameraConfigurationInteractorInputProtocol?, router: RecordingCameraConfigurationWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
