//
//  RecordingCameraConfigurationViewController.swift
//  vimojo
//
//  Created Jesus Huerta on 19/01/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecordingCameraConfigurationViewController: UIViewController, RecordingCameraConfigurationViewProtocol {
    
    // MARK: Outlets
    @IBOutlet weak var cameraProButton: UIButton!
    @IBOutlet weak var cameraBasicButton: UIButton!
    @IBOutlet weak var sevenTwentyResolutionButton: UIButton!
    @IBOutlet weak var oneEightyResolutionButton: UIButton!
	@IBOutlet weak var fourKResolutionButton: UIButton!
	@IBOutlet weak var twentyFivefpsButton: UIButton!
    @IBOutlet weak var thirtyFpsButton: UIButton!
	@IBOutlet weak var sixtyFpsButton: UIButton!
    @IBOutlet weak var sixteenMbpsButton: UIButton!
    @IBOutlet weak var thirtyTwoMbpsButton: UIButton!
    
    // MARK: SSRadioControllers
    var cameraSSRBController: SSRadioButtonsController = SSRadioButtonsController()
    var resolutionSSRBController: SSRadioButtonsController = SSRadioButtonsController()
    var fpsSSRBController: SSRadioButtonsController = SSRadioButtonsController()
    var mbpsSSRBController: SSRadioButtonsController = SSRadioButtonsController()
    
    var cameraButtons: [UIButton] = []
    var resolutionButtons: [UIButton] = []
    var fpsButtons: [UIButton] = []
    var mbpsButtons: [UIButton] = []
    
    var presenter: RecordingCameraConfigurationPresenterProtocol?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpButtonsArray()
        setupSSControllers()
        presenter?.viewDidLoad()
    }
    func setupSSControllers() {
        cameraSSRBController.setButtonsArray(cameraButtons)
        resolutionSSRBController.setButtonsArray(resolutionButtons)
        fpsSSRBController.setButtonsArray(fpsButtons)
        mbpsSSRBController.setButtonsArray(mbpsButtons)
    }
    func setUpButtonsArray() {
        cameraButtons = [ cameraProButton, cameraBasicButton ]
        fpsButtons = [twentyFivefpsButton, thirtyFpsButton, sixtyFpsButton]
        mbpsButtons = [sixteenMbpsButton, thirtyTwoMbpsButton]
        resolutionButtons =
            [sevenTwentyResolutionButton
				, oneEightyResolutionButton, fourKResolutionButton]
    }
    // MARK: Actions
    @IBAction func cameraProPush(_ sender: Any)
    { presenter?.actionPush(with: .camera(.cameraPro)) }
    @IBAction func cameraBasicPush(_ sender: Any)
    { presenter?.actionPush(with: .camera(.cameraBasic)) }
    @IBAction func sevenTwentyResolutioPush(_ sender: Any)
    { presenter?.actionPush(with: .resolution(.sevenHundred)) }
    @IBAction func oneEightyResolutionPush(_ sender: Any)
    { presenter?.actionPush(with: .resolution(.oneThousand)) }
	@IBAction func fourKResolutionPush(_ sender: Any)
	{ presenter?.actionPush(with: .resolution(.fourThousand)) }
    @IBAction func twentyFivefpsPush(_ sender: Any)
    { presenter?.actionPush(with: .fps(.twentyFive)) }
    @IBAction func thirtyFpsPush(_ sender: Any)
    { presenter?.actionPush(with: .fps(.thirty)) }
	@IBAction func sixtyFpsPush(_ sender: Any)
	{ presenter?.actionPush(with: .fps(.sixty)) }
    @IBAction func sixteenMbpsButton(_ sender: Any)
    { presenter?.actionPush(with: .mbps(.sixteenMB)) }
    @IBAction func thirtyTwoMbpsPush(_ sender: Any)
    { presenter?.actionPush(with: .mbps(.thirtyTwoMB)) }
    @IBAction func okPush(_ sender: Any)
    { self.navigationController?.popViewController() }
    
    func setDefaultValues(loadedValues: RecordingCameraValues) {
        cameraSSRBController.pressed(cameraButtons[loadedValues.0.rawValue])
        resolutionSSRBController.pressed(resolutionButtons[loadedValues.1.rawValue])
        fpsSSRBController.pressed(fpsButtons[loadedValues.2.rawValue])
        mbpsSSRBController.pressed(mbpsButtons[loadedValues.3.rawValue])
    }
}
