//
//  RecordingCameraConfigurationViewController.swift
//  vimojo
//
//  Created Jesus Huerta on 19/01/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RecordingCameraConfigurationViewController: UIViewController, RecordingCameraConfigurationViewProtocol {

	var presenter: RecordingCameraConfigurationPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
