//
//  RecordingCameraConfigurationProtocols.swift
//  vimojo
//
//  Created Jesus Huerta on 19/01/2018.
//  Copyright © 2018 Videona. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RecordingCameraConfigurationWireframeProtocol: class {

}
//MARK: Presenter -
protocol RecordingCameraConfigurationPresenterProtocol: class {

    var interactor: RecordingCameraConfigurationInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol RecordingCameraConfigurationInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol RecordingCameraConfigurationInteractorInputProtocol: class {

    var presenter: RecordingCameraConfigurationInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol RecordingCameraConfigurationViewProtocol: class {

    var presenter: RecordingCameraConfigurationPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
