//
//  HandOffRouter.swift
//  LoginProject
//
//  Created Alejandro Arjonilla Garcia on 27.04.18.
//  Copyright © 2018 Alejandro Arjonilla Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HandOffRouter: HandOffWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HandOffViewController(nibName: nil, bundle: nil)
        let router = HandOffRouter()
        let presenter = HandOffPresenter(interface: view, router: router)
        
        view.presenter = presenter
        router.viewController = view
        
        return view
    }
    func navigateToRegister() {
        viewController?.show(RegisterRouter.createModule(), sender: nil)
    }
    func navigateToLogin() {
        viewController?.show(LoginRouter.createModule(), sender: nil)
    }
}
