//
//  HandOffViewController.swift
//  LoginProject
//
//  Created Alejandro Arjonilla Garcia on 27.04.18.
//  Copyright © 2018 Alejandro Arjonilla Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HandOffViewController: UIViewController, HandOffViewProtocol {

    var presenter: HandOffPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func registerTapped(_ sender: Any) { presenter?.showRegister() }
    @IBAction func loginTapped(_ sender: Any) { presenter?.showLogin() }
}
