//
//  HandOffPresenter.swift
//  LoginProject
//
//  Created Alejandro Arjonilla Garcia on 27.04.18.
//  Copyright © 2018 Alejandro Arjonilla Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HandOffPresenter: HandOffPresenterProtocol {

    weak private var view: HandOffViewProtocol?
    private let router: HandOffWireframeProtocol

    init(interface: HandOffViewProtocol, router: HandOffWireframeProtocol) {
        self.view = interface
        self.router = router
    }
    func showRegister() {
        router.navigateToRegister()
    }
    func showLogin() {
        router.navigateToLogin()
    }
}
