//
//  HandOffProtocols.swift
//  LoginProject
//
//  Created Alejandro Arjonilla Garcia on 27.04.18.
//  Copyright © 2018 Alejandro Arjonilla Garcia. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HandOffWireframeProtocol: class {
    func navigateToRegister()
    func navigateToLogin()
}
//MARK: Presenter -
protocol HandOffPresenterProtocol: class {
    func showRegister()
    func showLogin()
}

//MARK: View -
protocol HandOffViewProtocol: class {

  var presenter: HandOffPresenterProtocol?  { get set }
}
